In [1]:
!pip install pandas

import numpy as np
import pandas as pd

In [3]:
a = np.array([1,2,3])

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# GET DIMENSION

In [7]:
a.ndim

1

In [8]:
b.ndim

2

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('float64')

In [13]:
a.itemsize

4

In [14]:
b.itemsize

8

In [15]:
a.size

3

In [16]:
b.size

6

In [17]:
a.nbytes

12

In [18]:
b.nbytes

48

In [19]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a[1,6]

14

In [21]:
a[1, -2]

13

In [22]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
a[:, 2]

array([ 3, 10])

In [24]:
a[0, 1:6:2]

array([2, 4, 6])

In [25]:
a[1,5] = 20
print (a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [26]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [ ]:
# THREE D

In [27]:
b =np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# GET SPECIFIC ELEMENT

In [29]:
b[0,1,1]

4

In [30]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [31]:
b[0,1,1]

4

In [ ]:
# INITIALIZING DIFFERENT TYPES OF ARRAYS

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [36]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [37]:
np.full((2,2),99, float)

array([[99., 99.],
       [99., 99.]])

In [38]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
np.random.rand(4,2)

array([[0.47509268, 0.55364683],
       [0.49654325, 0.93976575],
       [0.56708986, 0.65341513],
       [0.11777516, 0.37725085]])